# CyberPot Resource Profile: Raspberry Pi 4/5
# Optimized for ARM64 devices with limited resources

# Resource Mode
CYBERPOT_RESOURCE_MODE=LOW

# Memory Configuration
CYBERPOT_ES_HEAP_SIZE=-Xms512m -Xmx512m
CYBERPOT_LS_HEAP_SIZE=-Xms256m -Xmx256m
CYBERPOT_ES_MEM_LIMIT=1g
CYBERPOT_KIBANA_MEM_LIMIT=512m
CYBERPOT_LS_MEM_LIMIT=512m

# Disk Configuration
CYBERPOT_LOG_RETENTION_DAYS=7
CYBERPOT_LOG_MAX_SIZE_MB=50

# Performance Configuration
CYBERPOT_MAP_UPDATE_INTERVAL=10000
CYBERPOT_CACHE_TTL=300
CYBERPOT_BATCH_SIZE=100

# Monitoring
CYBERPOT_MONITORING_ENABLED=false

# Elasticsearch Configuration
CYBERPOT_ES_SHARDS=1
CYBERPOT_ES_REPLICAS=0

# Logstash Configuration
CYBERPOT_LS_WORKERS=1
CYBERPOT_LS_BATCH_SIZE=250

# Profile Metadata
PROFILE_NAME="Raspberry Pi"
PROFILE_DESCRIPTION="Optimized for Raspberry Pi 4/5 with 4-8GB RAM"
PROFILE_MIN_RAM_GB=4
PROFILE_MIN_DISK_GB=64
